FROM rocker/tidyverse:4.2.1

# RUN apt update -y && apt install wget unzip build-essential -y --no-install-recommends

RUN Rscript -e "install.packages(c('RPostgres','markdown'))"

WORKDIR /home/rstudio